# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [1]:
!pip install gmaps
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

Requirement already satisfied: gmaps in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (0.9.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (7.6.5)
Requirement already satisfied: ipython>=5.3.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (8.4.0)
Requirement already satisfied: traitlets>=4.3.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (5.1.1)
Requirement already satisfied: six in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (1.16.0)
Requirement already satisfied: geojson>=2.0.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from gmaps) (2.5.0)
Requirement already satisfied: appnope in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: matplotlib-inline in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.1.6)
Requirement already satisfied: pickleshare in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: backcall in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: jedi>=0.16 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.18.1)
Requirement already satisfied: pygments>=2.4.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (2.11.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (3.0.20)
Requirement already satisfied: decorator in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (5.1.1)
Requirement already satisfied: pexpect>4.3 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (4.8.0)
Requirement already satisfied: stack-data in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->gmaps) (63.4.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.2)
Requirement already satisfied: nbformat>=4.2.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (5.5.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (0.2.0)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (6.15.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.0.0->gmaps) (1.0.0)
Requirement already satisfied: pyzmq>=17 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (23.2.0)
Requirement already satisfied: packaging in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (21.3)
Requirement already satisfied: jupyter-client>=6.1.12 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.12)
Requirement already satisfied: debugpy>=1.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.1)
Requirement already satisfied: psutil in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (5.9.0)
Requirement already satisfied: tornado>=6.1 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1)
Requirement already satisfied: nest-asyncio in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (1.5.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.3.0->gmaps) (0.8.3)
Requirement already satisfied: fastjsonschema in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.4.0)
Requirement already satisfied: jupyter_core in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.10.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: wcwidth in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.4.12)
Requirement already satisfied: asttokens in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython>=5.3.0->gmaps) (2.0.5)
Requirement already satisfied: executing in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython>=5.3.0->gmaps) (0.8.3)
Requirement already satisfied: pure-eval in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython>=5.3.0->gmaps) (0.2.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (21.4.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.2)
Requirement already satisfied: nbconvert>=5 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.4.4)
Requirement already satisfied: Send2Trash>=1.8.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.8.0)
Requirement already satisfied: prometheus-client in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.14.1)
Requirement already satisfied: argon2-cffi in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.3.0)
Requirement already satisfied: terminado>=0.8.3 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.13.1)
Requirement already satisfied: jinja2 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from packaging->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (3.0.9)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4)
Requirement already satisfied: mistune<2,>=0.8.1 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: bleach in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.1.0)
Requirement already satisfied: defusedxml in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.13)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: beautifulsoup4 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (4.11.1)
Requirement already satisfied: jupyterlab-pygments in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.1.2)
Requirement already satisfied: testpath in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.6.0)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.0.1)

Requirement already satisfied: argon2-cffi-bindings in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.3.1)
Requirement already satisfied: webencodings in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: pycparser in /Users/clemoncekhoury/opt/anaconda3/lib/python3.9/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.21)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [2]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Weather_Database/WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Cidreira,BR,-30.1811,-50.2056,63.57,92,100,20.98,overcast clouds
1,1,Dingle,PH,10.9995,122.6711,75.97,90,100,8.86,overcast clouds
2,2,Kismayo,SO,-0.3582,42.5454,77.36,83,11,13.00,few clouds
3,3,Castro,BR,-24.7911,-50.0119,65.89,86,100,5.46,overcast clouds
4,4,Tiksi,RU,71.6872,128.8694,12.07,87,100,15.12,overcast clouds

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [3]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is your desired minimum temperature for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is your desired maximum temperature for your trip? "))

What is your desired minimum temperature for your trip? 60
What is your desired maximum temperature for your trip? 90

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [4]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                       (city_data_df["Max Temp"] >= min_temp)]                              
# Display sample data
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Cidreira,BR,-30.1811,-50.2056,63.57,92,100,20.98,overcast clouds
1,1,Dingle,PH,10.9995,122.6711,75.97,90,100,8.86,overcast clouds
2,2,Kismayo,SO,-0.3582,42.5454,77.36,83,11,13.00,few clouds
3,3,Castro,BR,-24.7911,-50.0119,65.89,86,100,5.46,overcast clouds
5,5,Praia,CV,14.9215,-23.5087,79.34,73,0,18.41,clear sky
6,6,Atuona,PF,-9.8000,-139.0333,76.89,75,28,14.76,scattered clouds
7,7,Broken Hill,AU,-31.9500,141.4333,61.93,46,100,13.98,overcast clouds
12,12,Katsuura,JP,35.1333,140.3000,69.87,87,100,6.35,light rain
13,13,Hollins,US,37.3413,-79.9431,67.08,55,97,8.01,overcast clouds
15,15,Adrar,MR,20.5022,-10.0711,89.33,9,30,11.16,scattered clouds

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [5]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.isnull().sum()

# Display sample data
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Cidreira,BR,-30.1811,-50.2056,63.57,92,100,20.98,overcast clouds
1,1,Dingle,PH,10.9995,122.6711,75.97,90,100,8.86,overcast clouds
2,2,Kismayo,SO,-0.3582,42.5454,77.36,83,11,13.00,few clouds
3,3,Castro,BR,-24.7911,-50.0119,65.89,86,100,5.46,overcast clouds
5,5,Praia,CV,14.9215,-23.5087,79.34,73,0,18.41,clear sky
...,...,...,...,...,...,...,...,...,...,...
692,692,Kathu,TH,7.9178,98.3332,81.75,89,100,13.31,moderate rain
694,694,Trebisacce,IT,39.8708,16.5312,64.22,61,0,3.04,clear sky
696,696,Catalao,BR,-18.1658,-47.9464,83.52,27,57,6.67,broken clouds
697,697,Nova Londrina,BR,-22.7658,-52.9850,79.81,67,100,8.66,overcast clouds
698,698,Casablanca,MA,33.5928,-7.6192,73.62,69,47,4.00,scattered clouds

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [6]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# Display sample data
hotel_df.head(10)

           City Country  Max Temp Current Description      Lat       Lng
0      Cidreira      BR     63.57     overcast clouds -30.1811  -50.2056
1        Dingle      PH     75.97     overcast clouds  10.9995  122.6711
2       Kismayo      SO     77.36          few clouds  -0.3582   42.5454
3        Castro      BR     65.89     overcast clouds -24.7911  -50.0119
5         Praia      CV     79.34           clear sky  14.9215  -23.5087
6        Atuona      PF     76.89    scattered clouds  -9.8000 -139.0333
7   Broken Hill      AU     61.93     overcast clouds -31.9500  141.4333
12     Katsuura      JP     69.87          light rain  35.1333  140.3000
13      Hollins      US     67.08     overcast clouds  37.3413  -79.9431
15        Adrar      MR     89.33    scattered clouds  20.5022  -10.0711

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [7]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Cidreira,BR,63.57,overcast clouds,-30.1811,-50.2056,
1,Dingle,PH,75.97,overcast clouds,10.9995,122.6711,
2,Kismayo,SO,77.36,few clouds,-0.3582,42.5454,
3,Castro,BR,65.89,overcast clouds,-24.7911,-50.0119,
5,Praia,CV,79.34,clear sky,14.9215,-23.5087,
6,Atuona,PF,76.89,scattered clouds,-9.8000,-139.0333,
7,Broken Hill,AU,61.93,overcast clouds,-31.9500,141.4333,
12,Katsuura,JP,69.87,light rain,35.1333,140.3000,
13,Hollins,US,67.08,overcast clouds,37.3413,-79.9431,
15,Adrar,MR,89.33,scattered clouds,20.5022,-10.0711,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [8]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [9]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Cidreira,BR,63.57,overcast clouds,-30.1811,-50.2056,Hotel Castelo
1,Dingle,PH,75.97,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
2,Kismayo,SO,77.36,few clouds,-0.3582,42.5454,Agan-Hotel
3,Castro,BR,65.89,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
5,Praia,CV,79.34,clear sky,14.9215,-23.5087,LT Aparthotel
6,Atuona,PF,76.89,scattered clouds,-9.8000,-139.0333,Villa Enata
7,Broken Hill,AU,61.93,overcast clouds,-31.9500,141.4333,Royal Exchange Hotel
12,Katsuura,JP,69.87,light rain,35.1333,140.3000,Katsuura Hotel Mikazuki
13,Hollins,US,67.08,overcast clouds,37.3413,-79.9431,"Country Inn & Suites by Radisson, Roanoke, VA"
15,Adrar,MR,89.33,scattered clouds,20.5022,-10.0711,

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [11]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df =  hotel_df.loc[(hotel_df["Hotel Name"]!='')]

# Display sample data
clean_hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Cidreira,BR,63.57,overcast clouds,-30.1811,-50.2056,Hotel Castelo
1,Dingle,PH,75.97,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
2,Kismayo,SO,77.36,few clouds,-0.3582,42.5454,Agan-Hotel
3,Castro,BR,65.89,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
5,Praia,CV,79.34,clear sky,14.9215,-23.5087,LT Aparthotel

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [ ]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [12]:
# Set the file name.
output_data_file = "WeatherPy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [13]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [14]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

['\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Castelo</dd>\n<dt>City</dt><dd>Cidreira</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 63.57 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>SEGAYA PROPERTY</dd>\n<dt>City</dt><dd>Dingle</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.97 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Agan-Hotel</dd>\n<dt>City</dt><dd>Kismayo</dd>\n<dt>Country</dt><dd>SO</dd>\n<dt>Current Weather</dt><dd>few clouds and 77.36 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>CHACARA BAILLY</dd>\n<dt>City</dt><dd>Castro</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 65.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>LT Aparthotel</dd>\n<dt>City</dt><dd>Praia</dd>\n<dt>Country</dt><dd>CV</dd>\n<dt>Current Weather</dt><dd>clear sky and 79.34 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Villa Enata</dd>\n<dt>City</dt><dd>Atuona</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 76.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Royal Exchange Hotel</dd>\n<dt>City</dt><dd>Broken Hill</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 61.93 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Katsuura Hotel Mikazuki</dd>\n<dt>City</dt><dd>Katsuura</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Current Weather</dt><dd>light rain and 69.87 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Country Inn & Suites by Radisson, Roanoke, VA</dd>\n<dt>City</dt><dd>Hollins</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 67.08 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Majestic Oasis Apartments</dd>\n<dt>City</dt><dd>Port Augusta</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Current Weather</dt><dd>moderate rain and 64.6 °F</dd>\n</dl>\n']

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [15]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat       Lng
0  -30.1811  -50.2056
1   10.9995  122.6711
2   -0.3582   42.5454
3  -24.7911  -50.0119
5   14.9215  -23.5087
6   -9.8000 -139.0333
7  -31.9500  141.4333
12  35.1333  140.3000
13  37.3413  -79.9431
18 -32.5000  137.7667

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [20]:
# Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, hotel_info)

# Create a figure to add the Google map as a layer
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# Display the figure containing the map
fig

Figure(layout=FigureLayout(height='420px'))